this_dot_r  Query {
  _mongooseOptions: {},
  _transforms: [],
  _hooks: Kareem { _pres: Map(0) {}, _posts: Map(0) {} },
  _execCount: 1,
  mongooseCollection: Collection {
    collection: Collection { db: [Db], s: [Object], client: [MongoClient] },
    Promise: [Function: Promise],
    modelName: 'Review',
    _closed: false,
    opts: {
      autoIndex: true,
      autoCreate: true,
      autoSearchIndex: false,
      schemaUserProvidedOptions: [Object],
      capped: false,
      Promise: undefined,
      '$wasForceClosed': undefined
    },
    name: 'reviews',
    collectionName: 'reviews',
    conn: NativeConnection {
      base: [Mongoose],
      collections: [Object],
      models: [Object],
      config: {},
      replica: false,
      options: null,
      otherDbs: [],
      relatedDbs: {},
      states: [Object: null prototype],
      _readyState: 1,
      _closeCalled: undefined,
      _hasOpened: true,
      plugins: [],
      id: 0,
      _queue: [],
      _listening: false,
      _lastHeartbeatAt: 1781396042754,
      _connectionOptions: [Object],
      _connectionString: 'mongodb+srv://nonoy:YR79VOozOijXS38b@cluster0.ghalmwu.mongodb.net/natours?appName=Cluster0',
      client: [MongoClient],
      '$initialConnection': [Promise],
      db: [Db],
      host: 'ac-r4fclmb-shard-00-00.ghalmwu.mongodb.net',
      port: 27017,
      name: 'natours',
      Symbol(mongoose:defaultConnection): true
    },
    queue: [],
    buffer: false,
    emitter: EventEmitter {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      Symbol(shapeMode): false,
      Symbol(kCapture): false
    }
  },
  model: Model { Review },
  schema: Schema {
    obj: {
      review: [Object],
      rating: [Object],
      createdAt: [Object],
      tour: [Object],
      user: [Object]
    },
    paths: {
      review: [SchemaString],
      rating: [SchemaNumber],
      createdAt: [SchemaDate],
      tour: [SchemaObjectId],
      user: [SchemaObjectId],
      _id: [SchemaObjectId],
      __v: [SchemaNumber]
    },
    aliases: {},
    subpaths: {},
    virtuals: { id: [VirtualType] },
    singleNestedPaths: {},
    nested: {},
    inherits: {},
    callQueue: [],
    _indexes: [],
    _searchIndexes: [],
    methods: {},
    methodOptions: {},
    statics: { calcAverageRatings: [AsyncFunction (anonymous)] },
    tree: {
      review: [Object],
      rating: [Object],
      createdAt: [Object],
      tour: [Object],
      user: [Object],
      _id: [Object],
      __v: [Function: Number],
      id: [VirtualType]
    },
    query: {},
    childSchemas: [],
    plugins: [ [Object], [Object], [Object], [Object] ],
    '$id': 4,
    mapPaths: [],
    encryptedFields: {},
    s: { hooks: [Kareem] },
    _userProvidedOptions: { toJSON: [Object], toObject: [Object] },
    options: {
      strict: true,
      strictQuery: false,
      bufferCommands: true,
      capped: false,
      versionKey: '__v',
      optimisticConcurrency: false,
      minimize: true,
      autoIndex: null,
      discriminatorKey: '__t',
      shardKey: null,
      read: null,
      validateBeforeSave: true,
      validateModifiedOnly: false,
      _id: true,
      id: true,
      typeKey: 'type',
      toJSON: [Object],
      toObject: [Object],
      pluralization: true
    },
    '$globalPluginsApplied': true
  },
  op: 'findOne',
  options: { new: true, runValidators: true },
  _conditions: { _id: '6a2d5dccec946a59b24bdce5' },
  _fields: undefined,
  _updateDoc: undefined,
  _path: undefined,
  _distinctDoc: undefined,
  _collection: NodeCollection {
    collection: Collection {
      collection: [Collection],
      Promise: [Function: Promise],
      modelName: 'Review',
      _closed: false,
      opts: [Object],
      name: 'reviews',
      collectionName: 'reviews',
      conn: [NativeConnection],
      queue: [],
      buffer: false,
      emitter: [EventEmitter]
    },
    collectionName: 'reviews'
  },
  _traceFunction: undefined,
  '$useProjection': true,
  _updateIsShared: true,
  Symbol(mongoose#Query#update): { rating: 4 }
}